server:
  port: 8585
  servlet:
    context-path: /crb-service


spring:
  application:
    name: crb service
  datasource:
    url: jdbc:h2:file:./db/crb_dev_db;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password: root
# H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: false #true, false
    hibernate:
      ddl-auto: none #none, create-drop, create, update
# schema.sql and data.sql execute
  sql:
    init:
      mode: always
      continue-on-error: true




## H2-DB open in browser
## http://localhost:8585/crb-service/h2-console