-- CREATE SCHEMA IF NOT EXISTS CRB_DEV_DB;
-- SHOW TABLES;
-- SHOW COLUMNS FROM CONFERENCE_ROOM;
-- SHOW COLUMNS FROM ROOM_BOOKING_HISTORY

DROP TABLE IF EXISTS CONFERENCE_ROOM_SLOTS;
DROP TABLE IF EXISTS MAINTENANCE_SETTINGS;
DROP TABLE IF EXISTS ROOM_BOOKING_HISTORY;
DROP TABLE IF EXISTS CONFERENCE_ROOM;

CREATE TABLE IF NOT EXISTS CONFERENCE_ROOM
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME                VARCHAR(50) NOT NULL             ,
    CODE                VARCHAR(3) NOT NULL              ,
    CAPACITY            INT NOT NULL                     , -- (people)
    SLOT_INTERVAL       INT NOT NULL                     , -- (minutes)
    WORKING_HOUR_WINDOW VARCHAR(20) NOT NULL             , -- (room active in operation hour, ex: 8 hours)
    -- AUDIT Fields
    CREATED_BY          VARCHAR(20) NOT NULL             ,
    CREATED_DATE        TIMESTAMP(6) WITH TIME ZONE      ,
    LAST_MODIFIED_BY    VARCHAR(20) NULL                 ,
    LAST_MODIFIED_DATE  TIMESTAMP(6) WITH TIME ZONE
);


CREATE TABLE IF NOT EXISTS CONFERENCE_ROOM_SLOTS
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONFERENCE_ROOM_ID  BIGINT                           ,
    SLOT_DATE           VARCHAR(20) NOT NULL             ,
    SLOT_TIME_WINDOW    VARCHAR(20) NOT NULL             ,
    STATUS              INT NOT NULL                     ,
    -- AUDIT Fields
    CREATED_BY          VARCHAR(20) NOT NULL             ,
    CREATED_DATE        TIMESTAMP(6) WITH TIME ZONE      ,
    CONSTRAINT FK_1_CONFERENCE_ROOM_ID FOREIGN KEY (CONFERENCE_ROOM_ID) REFERENCES CONFERENCE_ROOM (ID)
);


CREATE TABLE IF NOT EXISTS MAINTENANCE_SETTINGS
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONFERENCE_ROOM_ID  BIGINT                           ,
    MAINTENANCE_SLOT    VARCHAR(20) NOT NULL             ,
    -- AUDIT Fields
    CREATED_BY          VARCHAR(20) NOT NULL             ,
    CREATED_DATE        TIMESTAMP(6) WITH TIME ZONE      ,
    LAST_MODIFIED_BY    VARCHAR(20) NULL                 ,
    LAST_MODIFIED_DATE  TIMESTAMP(6) WITH TIME ZONE      ,
    CONSTRAINT FK_2_CONFERENCE_ROOM_ID FOREIGN KEY (CONFERENCE_ROOM_ID) REFERENCES CONFERENCE_ROOM (ID)
);


CREATE TABLE IF NOT EXISTS ROOM_BOOKING_HISTORY
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONFERENCE_ROOM_ID  BIGINT NOT NULL                  ,
    MEETING_TITLE       VARCHAR(255) NOT NULL            ,
    CONATCT_NUMBER      VARCHAR(20) NOT NULL             ,
    CONATCT_EMAIL       VARCHAR(20)                      ,
    NO_OF_PARTICIPANTS  INT                              ,
    START_TIME          TIMESTAMP(6)                     ,
    END_TIME            TIMESTAMP(6)                     ,
    SLOT_IDS            VARCHAR(100) NOT NULL            ,
    CREATED_BY          VARCHAR(20) NOT NULL             ,
    CREATED_DATE        TIMESTAMP(6) WITH TIME ZONE      ,
    CONSTRAINT FK_3_CONFERENCE_ROOM_ID FOREIGN KEY (CONFERENCE_ROOM_ID) REFERENCES CONFERENCE_ROOM (ID)
);